<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/06/14 12:45:35

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=pwnedbox.fr;dbname=projet2k11;port:3306',
  'username' => 'projet2k11',
  'password' => 'supinfoprojet2k11password',
  'name' => 'doctrine',
)),);
