generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Vehicle
    theme:                 admin
    non_verbose_templates: false
    with_show:             true
    singular:              ~
    plural:                ~
    route_prefix:          vehicle
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        display: [fullname, _agency]
      filter:  
        display: [brand, model, next_verif_start]
      form:    ~
      edit:    ~
      new:     ~
