<?php

/**
 * BaseFrm_TopicView
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $topic_id
 * @property sfGuardUser $sfGuardUser
 * @property Frm_Topic $Frm_Topic
 * 
 * @method integer       getUserId()      Returns the current record's "user_id" value
 * @method integer       getTopicId()     Returns the current record's "topic_id" value
 * @method sfGuardUser   getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method Frm_Topic     getFrmTopic()    Returns the current record's "Frm_Topic" value
 * @method Frm_TopicView setUserId()      Sets the current record's "user_id" value
 * @method Frm_TopicView setTopicId()     Sets the current record's "topic_id" value
 * @method Frm_TopicView setSfGuardUser() Sets the current record's "sfGuardUser" value
 * @method Frm_TopicView setFrmTopic()    Sets the current record's "Frm_Topic" value
 * 
 * @package    d
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseFrm_TopicView extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('frm__topic_view');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('topic_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('type', 'MySIAM');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Frm_Topic', array(
             'local' => 'topic_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}