<?php

/**
 * BasesfGuardUserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $sf_guard_user_id
 * @property integer $agency_id
 * @property string $first_name
 * @property string $last_name
 * @property timestamp $birthday
 * @property integer $type
 * @property string $mail
 * @property string $phone
 * @property string $mobile
 * @property sfGuardUser $sfGuardUser
 * @property Agency $Agency
 * 
 * @method integer            getId()               Returns the current record's "id" value
 * @method integer            getSfGuardUserId()    Returns the current record's "sf_guard_user_id" value
 * @method integer            getAgencyId()         Returns the current record's "agency_id" value
 * @method string             getFirstName()        Returns the current record's "first_name" value
 * @method string             getLastName()         Returns the current record's "last_name" value
 * @method timestamp          getBirthday()         Returns the current record's "birthday" value
 * @method integer            getType()             Returns the current record's "type" value
 * @method string             getMail()             Returns the current record's "mail" value
 * @method string             getPhone()            Returns the current record's "phone" value
 * @method string             getMobile()           Returns the current record's "mobile" value
 * @method sfGuardUser        getSfGuardUser()      Returns the current record's "sfGuardUser" value
 * @method Agency             getAgency()           Returns the current record's "Agency" value
 * @method sfGuardUserProfile setId()               Sets the current record's "id" value
 * @method sfGuardUserProfile setSfGuardUserId()    Sets the current record's "sf_guard_user_id" value
 * @method sfGuardUserProfile setAgencyId()         Sets the current record's "agency_id" value
 * @method sfGuardUserProfile setFirstName()        Sets the current record's "first_name" value
 * @method sfGuardUserProfile setLastName()         Sets the current record's "last_name" value
 * @method sfGuardUserProfile setBirthday()         Sets the current record's "birthday" value
 * @method sfGuardUserProfile setType()             Sets the current record's "type" value
 * @method sfGuardUserProfile setMail()             Sets the current record's "mail" value
 * @method sfGuardUserProfile setPhone()            Sets the current record's "phone" value
 * @method sfGuardUserProfile setMobile()           Sets the current record's "mobile" value
 * @method sfGuardUserProfile setSfGuardUser()      Sets the current record's "sfGuardUser" value
 * @method sfGuardUserProfile setAgency()           Sets the current record's "Agency" value
 * 
 * @package    d
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BasesfGuardUserProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user_profile');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('sf_guard_user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('agency_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('first_name', 'string', 64, array(
             'type' => 'string',
             'length' => 64,
             ));
        $this->hasColumn('last_name', 'string', 64, array(
             'type' => 'string',
             'length' => 64,
             ));
        $this->hasColumn('birthday', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('type', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('mail', 'string', 64, array(
             'type' => 'string',
             'length' => 64,
             ));
        $this->hasColumn('phone', 'string', 15, array(
             'type' => 'string',
             'length' => 15,
             ));
        $this->hasColumn('mobile', 'string', 15, array(
             'type' => 'string',
             'length' => 15,
             ));

        $this->option('type', 'MySIAM');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'sf_guard_user_id',
             'foreign' => 'id'));

        $this->hasOne('Agency', array(
             'local' => 'agency_id',
             'foreign' => 'id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'first_name',
              1 => 'last_name',
             ),
             ));
        $this->actAs($sluggable0);
    }
}