<?php

/**
 * BaseCommunityComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property integer $post_id
 * @property clob $content
 * @property timestamp $date
 * @property CommunityPost $CommunityPost
 * 
 * @method integer          getId()            Returns the current record's "id" value
 * @method integer          getUserId()        Returns the current record's "user_id" value
 * @method integer          getPostId()        Returns the current record's "post_id" value
 * @method clob             getContent()       Returns the current record's "content" value
 * @method timestamp        getDate()          Returns the current record's "date" value
 * @method CommunityPost    getCommunityPost() Returns the current record's "CommunityPost" value
 * @method CommunityComment setId()            Sets the current record's "id" value
 * @method CommunityComment setUserId()        Sets the current record's "user_id" value
 * @method CommunityComment setPostId()        Sets the current record's "post_id" value
 * @method CommunityComment setContent()       Sets the current record's "content" value
 * @method CommunityComment setDate()          Sets the current record's "date" value
 * @method CommunityComment setCommunityPost() Sets the current record's "CommunityPost" value
 * 
 * @package    d
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseCommunityComment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('community_comment');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('post_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('content', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CommunityPost', array(
             'local' => 'post_id',
             'foreign' => 'id'));
    }
}