<?php

/**
 * BaseFrmTopic
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property boolean $is_sticked
 * @property boolean $is_locked
 * @property integer $forum_id
 * @property integer $latest_post_id
 * @property integer $user_id
 * @property integer $nb_posts
 * @property integer $nb_views
 * @property FrmForum $FrmForum
 * @property FrmPost $FrmPost
 * @property sfGuardUser $sfGuardUser
 * @property Doctrine_Collection $FrmTopicView
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method string              getTitle()          Returns the current record's "title" value
 * @method boolean             getIsSticked()      Returns the current record's "is_sticked" value
 * @method boolean             getIsLocked()       Returns the current record's "is_locked" value
 * @method integer             getForumId()        Returns the current record's "forum_id" value
 * @method integer             getLatestPostId()   Returns the current record's "latest_post_id" value
 * @method integer             getUserId()         Returns the current record's "user_id" value
 * @method integer             getNbPosts()        Returns the current record's "nb_posts" value
 * @method integer             getNbViews()        Returns the current record's "nb_views" value
 * @method FrmForum            getFrmForum()       Returns the current record's "FrmForum" value
 * @method FrmPost             getFrmPost()        Returns the current record's "FrmPost" value
 * @method sfGuardUser         getSfGuardUser()    Returns the current record's "sfGuardUser" value
 * @method Doctrine_Collection getFrmTopicView()   Returns the current record's "FrmTopicView" collection
 * @method FrmTopic            setId()             Sets the current record's "id" value
 * @method FrmTopic            setTitle()          Sets the current record's "title" value
 * @method FrmTopic            setIsSticked()      Sets the current record's "is_sticked" value
 * @method FrmTopic            setIsLocked()       Sets the current record's "is_locked" value
 * @method FrmTopic            setForumId()        Sets the current record's "forum_id" value
 * @method FrmTopic            setLatestPostId()   Sets the current record's "latest_post_id" value
 * @method FrmTopic            setUserId()         Sets the current record's "user_id" value
 * @method FrmTopic            setNbPosts()        Sets the current record's "nb_posts" value
 * @method FrmTopic            setNbViews()        Sets the current record's "nb_views" value
 * @method FrmTopic            setFrmForum()       Sets the current record's "FrmForum" value
 * @method FrmTopic            setFrmPost()        Sets the current record's "FrmPost" value
 * @method FrmTopic            setSfGuardUser()    Sets the current record's "sfGuardUser" value
 * @method FrmTopic            setFrmTopicView()   Sets the current record's "FrmTopicView" collection
 * 
 * @package    d
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseFrmTopic extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('frm_topic');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('is_sticked', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('is_locked', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('forum_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('latest_post_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('nb_posts', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('nb_views', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));

        $this->option('type', 'MySIAM');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('FrmForum', array(
             'local' => 'forum_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('FrmPost', array(
             'local' => 'latest_post_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasMany('FrmTopicView', array(
             'local' => 'id',
             'foreign' => 'topic_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'title',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}