<?php

/**
 * BaseVehicleVerification
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $vehicle_id
 * @property timestamp $date_start
 * @property timestamp $date_end
 * @property Vehicle $Vehicle
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method integer             getVehicleId()  Returns the current record's "vehicle_id" value
 * @method timestamp           getDateStart()  Returns the current record's "date_start" value
 * @method timestamp           getDateEnd()    Returns the current record's "date_end" value
 * @method Vehicle             getVehicle()    Returns the current record's "Vehicle" value
 * @method VehicleVerification setId()         Sets the current record's "id" value
 * @method VehicleVerification setVehicleId()  Sets the current record's "vehicle_id" value
 * @method VehicleVerification setDateStart()  Sets the current record's "date_start" value
 * @method VehicleVerification setDateEnd()    Sets the current record's "date_end" value
 * @method VehicleVerification setVehicle()    Sets the current record's "Vehicle" value
 * 
 * @package    d
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseVehicleVerification extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vehicle_verification');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('vehicle_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('date_start', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('date_end', 'timestamp', null, array(
             'type' => 'timestamp',
             ));

        $this->option('type', 'MySIAM');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Vehicle', array(
             'local' => 'vehicle_id',
             'foreign' => 'id'));
    }
}