<?php

/**
 * BaseFrmRank
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $nb_posts
 * @property varchar $image
 * @property string $title
 * 
 * @method integer getNbPosts()  Returns the current record's "nb_posts" value
 * @method varchar getImage()    Returns the current record's "image" value
 * @method string  getTitle()    Returns the current record's "title" value
 * @method FrmRank setNbPosts()  Sets the current record's "nb_posts" value
 * @method FrmRank setImage()    Sets the current record's "image" value
 * @method FrmRank setTitle()    Sets the current record's "title" value
 * 
 * @package    d
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseFrmRank extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('frm_rank');
        $this->hasColumn('nb_posts', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('image', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('title', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 30,
             ));

        $this->option('type', 'MySIAM');
    }

    public function setUp()
    {
        parent::setUp();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'title',
             ),
             ));
        $this->actAs($sluggable0);
    }
}