<?php

/**
 * BaseFormationCenter
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $image
 * @property string $address
 * @property string $address_bis
 * @property integer $capacity
 * 
 * @method integer         getId()          Returns the current record's "id" value
 * @method string          getName()        Returns the current record's "name" value
 * @method string          getImage()       Returns the current record's "image" value
 * @method string          getAddress()     Returns the current record's "address" value
 * @method string          getAddressBis()  Returns the current record's "address_bis" value
 * @method integer         getCapacity()    Returns the current record's "capacity" value
 * @method FormationCenter setId()          Sets the current record's "id" value
 * @method FormationCenter setName()        Sets the current record's "name" value
 * @method FormationCenter setImage()       Sets the current record's "image" value
 * @method FormationCenter setAddress()     Sets the current record's "address" value
 * @method FormationCenter setAddressBis()  Sets the current record's "address_bis" value
 * @method FormationCenter setCapacity()    Sets the current record's "capacity" value
 * 
 * @package    d
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseFormationCenter extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('formation_center');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 64, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 64,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('address', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('address_bis', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('capacity', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('type', 'MySIAM');
    }

    public function setUp()
    {
        parent::setUp();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($sluggable0);
    }
}