<?php

/**
 * BaseAgencyRoom
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $agency_id
 * @property integer $capacity
 * @property Doctrine_Collection $Agency
 * 
 * @method integer             getId()        Returns the current record's "id" value
 * @method string              getName()      Returns the current record's "name" value
 * @method integer             getAgencyId()  Returns the current record's "agency_id" value
 * @method integer             getCapacity()  Returns the current record's "capacity" value
 * @method Doctrine_Collection getAgency()    Returns the current record's "Agency" collection
 * @method AgencyRoom          setId()        Sets the current record's "id" value
 * @method AgencyRoom          setName()      Sets the current record's "name" value
 * @method AgencyRoom          setAgencyId()  Sets the current record's "agency_id" value
 * @method AgencyRoom          setCapacity()  Sets the current record's "capacity" value
 * @method AgencyRoom          setAgency()    Sets the current record's "Agency" collection
 * 
 * @package    d
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseAgencyRoom extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('agency_room');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 64, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 64,
             ));
        $this->hasColumn('agency_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('capacity', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('type', 'MySIAM');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Agency', array(
             'local' => 'agency_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($sluggable0);
    }
}