<?php

/**
 * BaseSingleOffer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $short_description
 * @property clob $description
 * @property float $price
 * @property integer $category_id
 * @property boolean $is_active
 * @property Category $Category
 * 
 * @method integer     getId()                Returns the current record's "id" value
 * @method string      getName()              Returns the current record's "name" value
 * @method string      getShortDescription()  Returns the current record's "short_description" value
 * @method clob        getDescription()       Returns the current record's "description" value
 * @method float       getPrice()             Returns the current record's "price" value
 * @method integer     getCategoryId()        Returns the current record's "category_id" value
 * @method boolean     getIsActive()          Returns the current record's "is_active" value
 * @method Category    getCategory()          Returns the current record's "Category" value
 * @method SingleOffer setId()                Sets the current record's "id" value
 * @method SingleOffer setName()              Sets the current record's "name" value
 * @method SingleOffer setShortDescription()  Sets the current record's "short_description" value
 * @method SingleOffer setDescription()       Sets the current record's "description" value
 * @method SingleOffer setPrice()             Sets the current record's "price" value
 * @method SingleOffer setCategoryId()        Sets the current record's "category_id" value
 * @method SingleOffer setIsActive()          Sets the current record's "is_active" value
 * @method SingleOffer setCategory()          Sets the current record's "Category" value
 * 
 * @package    d
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseSingleOffer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('single_offer');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 64, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 64,
             ));
        $this->hasColumn('short_description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('price', 'float', 7, array(
             'type' => 'float',
             'scale' => 2,
             'length' => 7,
             ));
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             ));

        $this->option('type', 'MySIAM');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($sluggable0);
    }
}