<?php

/**
 * BaseFrmTopicView
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $topic_id
 * @property sfGuardUser $sfGuardUser
 * @property FrmTopic $FrmTopic
 * 
 * @method integer      getUserId()      Returns the current record's "user_id" value
 * @method integer      getTopicId()     Returns the current record's "topic_id" value
 * @method sfGuardUser  getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method FrmTopic     getFrmTopic()    Returns the current record's "FrmTopic" value
 * @method FrmTopicView setUserId()      Sets the current record's "user_id" value
 * @method FrmTopicView setTopicId()     Sets the current record's "topic_id" value
 * @method FrmTopicView setSfGuardUser() Sets the current record's "sfGuardUser" value
 * @method FrmTopicView setFrmTopic()    Sets the current record's "FrmTopic" value
 * 
 * @package    d
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseFrmTopicView extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('frm_TopicView');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('topic_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('type', 'MySIAM');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('FrmTopic', array(
             'local' => 'topic_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}