<?php

/**
 * BaseCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $short_description
 * @property clob $description
 * @property string $image
 * @property integer $category_id
 * @property boolean $is_active
 * @property Category $Category
 * @property Doctrine_Collection $Package
 * @property Doctrine_Collection $Offer
 * 
 * @method integer             getId()                Returns the current record's "id" value
 * @method string              getName()              Returns the current record's "name" value
 * @method string              getShortDescription()  Returns the current record's "short_description" value
 * @method clob                getDescription()       Returns the current record's "description" value
 * @method string              getImage()             Returns the current record's "image" value
 * @method integer             getCategoryId()        Returns the current record's "category_id" value
 * @method boolean             getIsActive()          Returns the current record's "is_active" value
 * @method Category            getCategory()          Returns the current record's "Category" value
 * @method Doctrine_Collection getPackage()           Returns the current record's "Package" collection
 * @method Doctrine_Collection getOffer()             Returns the current record's "Offer" collection
 * @method Category            setId()                Sets the current record's "id" value
 * @method Category            setName()              Sets the current record's "name" value
 * @method Category            setShortDescription()  Sets the current record's "short_description" value
 * @method Category            setDescription()       Sets the current record's "description" value
 * @method Category            setImage()             Sets the current record's "image" value
 * @method Category            setCategoryId()        Sets the current record's "category_id" value
 * @method Category            setIsActive()          Sets the current record's "is_active" value
 * @method Category            setCategory()          Sets the current record's "Category" value
 * @method Category            setPackage()           Sets the current record's "Package" collection
 * @method Category            setOffer()             Sets the current record's "Offer" collection
 * 
 * @package    d
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 64, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 64,
             ));
        $this->hasColumn('short_description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             ));

        $this->option('type', 'MySIAM');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id'));

        $this->hasMany('Package', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $this->hasMany('Offer', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($sluggable0);
    }
}