<?php

/**
 * BasePackageHasOffer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $package_id
 * @property integer $offer_id
 * @property Package $Package
 * @property Offer $Offer
 * 
 * @method integer         getId()         Returns the current record's "id" value
 * @method integer         getPackageId()  Returns the current record's "package_id" value
 * @method integer         getOfferId()    Returns the current record's "offer_id" value
 * @method Package         getPackage()    Returns the current record's "Package" value
 * @method Offer           getOffer()      Returns the current record's "Offer" value
 * @method PackageHasOffer setId()         Sets the current record's "id" value
 * @method PackageHasOffer setPackageId()  Sets the current record's "package_id" value
 * @method PackageHasOffer setOfferId()    Sets the current record's "offer_id" value
 * @method PackageHasOffer setPackage()    Sets the current record's "Package" value
 * @method PackageHasOffer setOffer()      Sets the current record's "Offer" value
 * 
 * @package    d
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BasePackageHasOffer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('package_has_offer');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('package_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('offer_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('type', 'MySIAM');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Package', array(
             'local' => 'package_id',
             'foreign' => 'id'));

        $this->hasOne('Offer', array(
             'local' => 'offer_id',
             'foreign' => 'id'));
    }
}