<?php

/**
 * BaseFormationSession
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $formation_type_id
 * @property integer $capacity
 * @property timestamp $date_start
 * @property timestamp $date_end
 * @property FormationType $FormationType
 * 
 * @method integer          getId()                Returns the current record's "id" value
 * @method string           getName()              Returns the current record's "name" value
 * @method integer          getFormationTypeId()   Returns the current record's "formation_type_id" value
 * @method integer          getCapacity()          Returns the current record's "capacity" value
 * @method timestamp        getDateStart()         Returns the current record's "date_start" value
 * @method timestamp        getDateEnd()           Returns the current record's "date_end" value
 * @method FormationType    getFormationType()     Returns the current record's "FormationType" value
 * @method FormationSession setId()                Sets the current record's "id" value
 * @method FormationSession setName()              Sets the current record's "name" value
 * @method FormationSession setFormationTypeId()   Sets the current record's "formation_type_id" value
 * @method FormationSession setCapacity()          Sets the current record's "capacity" value
 * @method FormationSession setDateStart()         Sets the current record's "date_start" value
 * @method FormationSession setDateEnd()           Sets the current record's "date_end" value
 * @method FormationSession setFormationType()     Sets the current record's "FormationType" value
 * 
 * @package    d
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseFormationSession extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('formation_session');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 64, array(
             'type' => 'string',
             'length' => 64,
             ));
        $this->hasColumn('formation_type_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('capacity', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('date_start', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('date_end', 'timestamp', null, array(
             'type' => 'timestamp',
             ));

        $this->option('type', 'MySIAM');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('FormationType', array(
             'local' => 'formation_type_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));
    }
}