<?php

/**
 * BasePackageLine
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $image
 * @property integer $package_id
 * @property Package $Package
 * 
 * @method integer     getId()         Returns the current record's "id" value
 * @method string      getName()       Returns the current record's "name" value
 * @method string      getImage()      Returns the current record's "image" value
 * @method integer     getPackageId()  Returns the current record's "package_id" value
 * @method Package     getPackage()    Returns the current record's "Package" value
 * @method PackageLine setId()         Sets the current record's "id" value
 * @method PackageLine setName()       Sets the current record's "name" value
 * @method PackageLine setImage()      Sets the current record's "image" value
 * @method PackageLine setPackageId()  Sets the current record's "package_id" value
 * @method PackageLine setPackage()    Sets the current record's "Package" value
 * 
 * @package    d
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BasePackageLine extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('package_line');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 64, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 64,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('package_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('type', 'MySIAM');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Package', array(
             'local' => 'package_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));
    }
}