<?php

/**
 * BaseCommunityCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property boolean $is_active
 * @property Doctrine_Collection $CommunityPost
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method string              getName()          Returns the current record's "name" value
 * @method string              getDescription()   Returns the current record's "description" value
 * @method boolean             getIsActive()      Returns the current record's "is_active" value
 * @method Doctrine_Collection getCommunityPost() Returns the current record's "CommunityPost" collection
 * @method CommunityCategory   setId()            Sets the current record's "id" value
 * @method CommunityCategory   setName()          Sets the current record's "name" value
 * @method CommunityCategory   setDescription()   Sets the current record's "description" value
 * @method CommunityCategory   setIsActive()      Sets the current record's "is_active" value
 * @method CommunityCategory   setCommunityPost() Sets the current record's "CommunityPost" collection
 * 
 * @package    d
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseCommunityCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('community_category');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 64, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 64,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             ));

        $this->option('type', 'MySIAM');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CommunityPost', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($sluggable0);
    }
}