listCategorySuccess:
    javascripts: [jquery/jquery.js, jquery/jquery.flexigrid.js]
    stylesheets: [flexigrid.pack.css]

listOfferSuccess:
    javascripts: [jquery/jquery.js, jquery/jquery.flexigrid.js]
    stylesheets: [flexigrid.pack.css]
    
listPackageSuccess:
    javascripts: [jquery/jquery.js, jquery/jquery.flexigrid.js]
    stylesheets: [flexigrid.pack.css]