all:
    javascripts: [jquery/jquery.js]
    
listCustomersSuccess:
    javascripts: [jquery/jquery.js, jquery/jquery.flexigrid.js]
    stylesheets: [flexigrid.pack.css]
    
listEmployeesSuccess:
    javascripts: [jquery/jquery.js, jquery/jquery.flexigrid.js]
    stylesheets: [flexigrid.pack.css]
    
listTeachersSuccess:
    javascripts: [jquery/jquery.js, jquery/jquery.flexigrid.js]
    stylesheets: [flexigrid.pack.css]
    
viewTeacherSuccess:
    javascripts: [jquery/jquery.js, jquery/jquery.flexigrid.js]
    stylesheets: [flexigrid.pack.css]
    
viewCustomerSuccess:
    javascripts: [jquery/jquery.js, jquery/jquery.flexigrid.js]
    stylesheets: [flexigrid.pack.css]