<?php

/**
 * AgencyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AgencyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AgencyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Agency');
    }
}