<?php

/**
 * Agency
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    d
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Agency extends BaseAgency
{
  public function __toString() 
  {
      return $this->getSlug();
  }
}
