<?php

/**
 * AgencyRoomTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AgencyRoomTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AgencyRoomTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AgencyRoom');
    }
}