<?php

/**
 * CategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Category');
    }
    
    static public function getActiveQuery()
    {
      return Doctrine_Query::create()
              ->from('Category c')
              ->where('is_active = ?', true);
    }
    
    static public function getActive()
    {
      return self::getActiveQuery()->execute();
    }
}