<?php

/**
 * CommunityCommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CommunityCommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CommunityCommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CommunityComment');
    }
}