<?php

/**
 * CommunityCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CommunityCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CommunityCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CommunityCategory');
    }
}