<?php

/**
 * CommunityPostTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CommunityPostTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CommunityPostTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CommunityPost');
    }
}