<?php

/**
 * ExamHasUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExamHasUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExamHasUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExamHasUser');
    }
    
    static public function getByExamQuery(Exam $exam)
    {
      return Doctrine_Query::create()->from('ExamHasUser ehs')->leftJoin('ehs.Exam e')->where('e.id = ?',$exam->getId());
    }
}