<?php

/**
 * FormationSessionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FormationSessionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FormationSessionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FormationSession');
    }
    
    /**
     * Get by Agency Query
     *
     * @param Agency $agency
     *
     * @return Doctrine_Query
     */
    static public function getByAgencyQuery(Agency $agency)
    {
      return Doctrine_Query::create()->from('FormationSession f')->leftJoin('f.Agency s')->where('s.id = ?', $agency->getId());
    }
    
    /**
     * Get by Teacher Query
     *
     * @param sfGuardUser $Teacher
     *
     * @return Doctrine_Collection
     */
    static public function getByTeacherQuery(sfGuardUser $Teacher)
    {
      //$datas = Doctrine_Query::create()->from('FormationHasTeacher fht')->where('fht.id',$Teacher->getId());
      
      return Doctrine_Query::create()
              ->from('FormationSession f')
              ->where('f.id IN ( SELECT fhd.formation_session_id FROM FormationHasTeacher fhd WHERE fhd.teacher_id = ? )', $Teacher->getId());
    }
    
    /**
     * get participations
     *
     * @param FormationSession  $formationSession
     * @param Integer           $filter
     *
     * @return Doctrine_Collection
     */
    static public function getParticipations(FormationSession $formationSession, $filter = FormationSession::PARTICIPATION_ALL)
    {
      $query = Doctrine_Query::create()
                ->from('FormationHasUser fhc')
                ->leftJoin('fhc.FormationSession fs')
                ->where('fs.id = ?', $formationSession->getId());
                
      if($filter == FormationSession::PARTICIPATION_VALIDATED)
      {
        $query->addWhere('fhc.is_valid = ?', true);
      } 
      elseif($filter = FormationSession::PARTICIPATION_NOT_VALIDATED)
      {
        $query->addWhere('fhc.is_valid = ?', false);
      }
      
      return $query->execute();
    }
    
    /**
     * get available customers
     *
     * @param FormationSession $formationSession
     * 
     * @return Array
     */
    static public function getAvailableCustomers(FormationSession $formationSession)
    {
      $agencyCutomers     = sfGuardUserProfileTable::getAgencyCustomersQuery($formationSession->getAgency())->execute();
      $sessionCustomers   = array();
      $availableCustomers = array();
      
      foreach($formationSession->getValidatedParticipations() as $current)
      {
        $sessionCustomers[] = $current->getUserId();
      }
      
      foreach($agencyCutomers as $customer) 
      {
        if(!in_array($customer->getSfGuardUserId(), $sessionCustomers))
        {
          $availableCustomers[$customer->getSfGuardUserId()] = $customer->getFullname();
        }
      }
      
      return $availableCustomers;
    }
    
    /**
     * get available Teachers
     *
     * @param FormationSession $formationSession
     * 
     * @return Array
     */
    static public function getAvailableTeachers(FormationSession $formationSession)
    {
      $agencyTeachers     = sfGuardUserProfileTable::getAgencyTeachersQuery($formationSession->getAgency())->execute();
      $sessionTeachers   = array();
      $availableTeachers = array();
      
      foreach($formationSession->getTeachersRegistrations() as $current)
      {
        $sessionTeachers[] = $current->getTeacherId();
      }
      
      foreach($agencyTeachers as $teacher) 
      {
        if(!in_array($teacher->getSfGuardUserId(), $sessionTeachers))
        {
          $availableTeachers[$teacher->getSfGuardUserId()] = $teacher->getFullname();
        }
      }
      
      return $availableTeachers;
    }
    
    /**
     * get vehicles reservations for given FormationSession
     *
     * @param FormationSession $formationSession
     *
     * @return Doctrine_collection
     */
    static public function getVehiclesReservations(FormationSession $formationSession)
    {
      return Doctrine_Query::create()
              ->from('FormationHasVehicle f')
              ->where('f.formation_session_id = ?', $formationSession->getId())
              ->execute();
    }
    
    /**
     * get teachers registrations for given FormationSession
     *
     * @param FormationSession $formationSession
     *
     * @return Doctrine_collection
     */
    static public function getTeachersRegistrations(FormationSession $formationSession)
    {
      return Doctrine_Query::create()
              ->from('FormationHasTeacher f')
              ->where('f.formation_session_id = ?', $formationSession->getId())
              ->execute();
    }
    
    /**
     * Get available vehicles 
     *
     * @param FormationSession $formationSession
     *
     * @return Array
     */
    static public function getAvailableVehicles(FormationSession $formationSession)
    {
      $agencyVehicles = VehicleTable::vehiclesByAgencyQuery($formationSession->getAgency()->getId())->execute();
      
      $sessionVehicles    = array();
      $availableVehicles  = array();
      
      foreach($formationSession->getVehiclesReservations() as $current)
      {
        $sessionVehicles[] = $current->getVehicleId();
      }
      
      foreach($agencyVehicles as $vehicle)
      {
        if(!in_array($vehicle->getId(), $sessionVehicles))
        {
          $availableVehicles[$vehicle->getId()] = '( '.$vehicle->getBrand().' - '. $vehicle->getModel() .' ) '.$vehicle->getName();
        }
      }
      
      return $availableVehicles;
    }
}