<?php

/**
 * FormationHasUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FormationHasUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FormationHasUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FormationHasUser');
    }

    static public function getMarksByUserId()
    {
      return Doctrine_Query::create()->from('FormationHasUser f')->where('f.user_id = ?', sfContext::getInstance()->getUser()->getGuardUser()->getId());
    }
}