<?php

/**
 * FormationSession
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    d
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class FormationSession extends BaseFormationSession
{
  public function __toString()
  {
    $toString = '';
    if($this->getName()) {
      return $this->getName();
    }
    
    if($this->getDateStart())
    {
      return $this->getDateStart();
    }
    
    return 'Formation Session #'.$this->getId();
  }
}
