<?php

/**
 * FormationCenterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FormationCenterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FormationCenterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FormationCenter');
    }
    
    static public function getByAgencyQuery(Agency $agency)
    {
      return Doctrine_Query::create()->from('FormationCenter c')
        ->leftJoin('c.Agency a')
        ->where('a.id = ?', $agency->getId());
    }
}