<?php

/**
 * FormationHasTeacherTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FormationHasTeacherTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FormationHasTeacherTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FormationHasTeacher');
    }
}