<?php

/**
 * FormationSessionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FormationSessionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FormationSessionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FormationSession');
    }
    
    static public function getByAgencyQuery(Agency $agency)
    {
      return Doctrine_Query::create()->from('FormationSession f')->leftJoin('f.Agency s')->where('s.id = ?', $agency->getId());
    }
}