<?php

/**
 * FormationHasVehicleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FormationHasVehicleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FormationHasVehicleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FormationHasVehicle');
    }
}