<?php

/**
 * FormationHasUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FormationHasUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FormationHasUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FormationHasUser');
    }
}