<?php

/**
 * FormationSession
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    d
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class FormationSession extends BaseFormationSession
{
  const PARTICIPATION_VALIDATED     = 1;
  const PARTICIPATION_NOT_VALIDATED = 2;
  const PARTICIPATION_ALL           = 3;
  
  protected $validatedParticipation     = false;
  protected $notValidatedParticipation  = false;
  
  protected $vehiclesReservations       = false;
  protected $teachersRegistrations      = false;
  
  /**
   * To String 
   *
   * @return String
   */
  public function __toString()
  {
    $toString = '';
    if($this->getName()) {
      return $this->getName();
    }
    
    if($this->getDateStart())
    {
      return $this->getDateStart();
    }
    
    return 'Formation Session #'.$this->getId();
  }
  
  /**
   * get validated participations
   *
   * @return Doctrine_Collection
   */
  public function getValidatedParticipations()
  {
    if(!$this->validatedParticipation)
    {
      $this->validatedParticipation = FormationSessionTable::getParticipations($this, FormationSession::PARTICIPATION_VALIDATED);
    }
    
    return $this->validatedParticipation;
  }
  
  /**
   * Get validated participations
   *
   * @return Doctrine_Collection
   */
  public function getNotValidatedParticipations()
  {
    if(!$this->notValidatedParticipation)
    {
      $this->notValidatedParticipation = FormationSessionTable::getParticipations($this, FormationSession::PARTICIPATION_NOT_VALIDATED);
    }
    
    return $this->notValidatedParticipation;
  }
  
  /**
   * Get teachers registrations
   *
   * @return Doctrine_Collection
   */
  public function getTeachersRegistrations()
  {
    if(!$this->teachersRegistrations)
    {
      $this->teachersRegistrations = FormationSessionTable::getTeachersRegistrations($this);
    }
    
    return $this->teachersRegistrations;
  }
  
  /**
   * Get vehicles reservation
   *
   * @return Doctrine_Collection
   */
  public function getVehiclesReservations()
  {
    if(!$this->vehiclesReservations)
    {
      $this->vehiclesReservations = FormationSessionTable::getVehiclesReservations($this);
    }
    
    return $this->vehiclesReservations;
  }
}
