<?php

/**
 * Frm_TopicViewTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Frm_TopicViewTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Frm_TopicViewTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Frm_TopicView');
    }
}