<?php

/**
 * Frm_CategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Frm_CategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Frm_CategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Frm_Category');
    }
}