<?php

/**
 * Frm_RankTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Frm_RankTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Frm_RankTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Frm_Rank');
    }
}