<?php

/**
 * Frm_ForumTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Frm_ForumTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Frm_ForumTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Frm_Forum');
    }
}