<?php

/**
 * Frm_AbuseLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Frm_AbuseLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Frm_AbuseLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Frm_AbuseLog');
    }
}