<?php

/**
 * Frm_RecommandationLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Frm_RecommandationLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Frm_RecommandationLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Frm_RecommandationLog');
    }
}