<?php

/**
 * Frm_PostTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Frm_PostTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Frm_PostTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Frm_Post');
    }
}