<?php

/**
 * Frm_TopicTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Frm_TopicTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Frm_TopicTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Frm_Topic');
    }
}