<?php

/**
 * FrmCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FrmCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FrmCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FrmCategory');
    }
}