<?php

/**
 * FrmForumTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FrmForumTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FrmForumTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FrmForum');
    }
}