<?php

/**
 * FrmPostTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FrmPostTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FrmPostTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FrmPost');
    }
}