<?php

/**
 * FrmRankTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FrmRankTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FrmRankTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FrmRank');
    }
}