<?php

/**
 * FrmTopicTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FrmTopicTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FrmTopicTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FrmTopic');
    }

    public function getTopicsByDate(Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()
                            ->from('FrmTopic f');
        }

        $alias = $q->getRootAlias();

        $q->addOrderBy($alias . '.created_at DESC');

        return $q;
    }
}