<?php

/**
 * FrmTopicViewTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FrmTopicViewTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FrmTopicViewTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FrmTopicView');
    }
}