<?php

/**
 * OfferTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OfferTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OfferTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Offer');
    }
    
    static public function getAllQuery()
    {
      return Doctrine_Query::create()->from('Offer');
    }
}