<?php

/**
 * PackagetestTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PackagetestTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PackagetestTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Packagetest');
    }
}