<?php

/**
 * PackageLineTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PackageLineTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PackageLineTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PackageLine');
    }
}