<?php

/**
 * sfGuardUserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    d
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class sfGuardUserProfile extends BasesfGuardUserProfile
{
  const TYPE_EMPLOYEE  = 1;
  const TYPE_CUSTOMER  = 2;
  const TYPE_TEACHER   = 3;
  
  public function __toString() { return $this->getFirstName() . $this->getLastName(); }
  
  public function getFullname() { return $this->getFirstName() . ' ' .  $this->getLastName(); }
}
