<?php

/**
 * SingleOfferTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SingleOfferTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SingleOfferTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SingleOffer');
    }
}