<?php

/**
 * TeacherUnavailabilityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TeacherUnavailabilityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TeacherUnavailabilityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TeacherUnavailability');
    }
}