<?php

/**
 * UserHasPackage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    d
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class UserHasPackage extends BaseUserHasPackage
{
  /**
   * Disable current package
   *
   * @return UserHasPackage
   */
  public function disable()
  {
    $this->setIsActive(false);
    
    return $this;
  }
  
  /**
   * Enable current package
   *
   * @return UserHasPackage
   */
  public function enable()
  {
    $this->setIsActive(true);
    
    return $this;
  }
}