<?php

/**
 * UserHasOfferTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserHasOfferTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserHasOfferTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserHasOffer');
    }
}