<?php

/**
 * VehicleVerificationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VehicleVerificationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VehicleVerificationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VehicleVerification');
    }
}