<?php

/**
 * VehicleTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VehicleTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VehicleTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VehicleType');
    }
}