generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardUserProfile
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_user_profile_employee
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        table_method:     getAllEmployees
        display:          [Agency, Fullname]
      filter:
        display:          [agency_id, first_name, last_name]
      form:
        class:            EmployeeForm
      edit:    ~
      new:     ~
