<?php

/**
 * sfGuardUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserTable extends PluginsfGuardUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUser');
    }
    
    /**
     * Get marks average
     *
     * @param Doctrine_Collection $usersCollection
     *
     * @return Array
     */
    static public function getMarksAverage(Doctrine_Collection $usersCollection, $type)
    {
      foreach($usersCollection as $user)
      {
        $averages[$user->getId()] = $user->getMarksAverage($type);
      }
      
      arsort($averages);
      
      return $averages;
    }
}