vehiclesSuccess:
    javascripts: [jquery/jquery.js, jquery/jquery.flexigrid.js]
    stylesheets: [flexigrid.pack.css]

listCustomersSuccess:
    javascripts: [jquery/jquery.js, jquery/jquery.flexigrid.js]
    stylesheets: [flexigrid.pack.css]
    
listEmployeesSuccess:
    javascripts: [jquery/jquery.js, jquery/jquery.flexigrid.js]
    stylesheets: [flexigrid.pack.css]
    
listFormationCenterSuccess:
    javascripts: [jquery/jquery.js, jquery/jquery.flexigrid.js]
    stylesheets: [flexigrid.pack.css]

listAgencyRoomSuccess:
    javascripts: [jquery/jquery.js, jquery/jquery.flexigrid.js]
    stylesheets: [flexigrid.pack.css]