vehiclesSuccess:
    javascripts: [jquery/jquery.js, jquery/jquery.flexigrid.js]
    stylesheets: [flexigrid.pack.css]

listCustomersSuccess:
    javascripts: [jquery/jquery.js, jquery/jquery.flexigrid.js]
    stylesheets: [flexigrid.pack.css]